### ISSUE TITLE
Feedback on documentation

### ISSUE THREAD

**Issue by toncho11** [ActiveLook/Activelook-API-Documentation#8]
I have worked on the integration of ENGO smart glasses with ESP32 and I noted a few things related to the documentation: 

1) Here I have a bit of a confusion. I am using these 16 bit UUIDs:

static BLEUUID GenericAccess_DeviceNameUUID((uint16_t)0x2a00);
static BLEUUID GenericAccess_AppearanceUUID((uint16_t)0x2a01); 
static BLEUUID GenericAccess_PeripheralUUID((uint16_t)0x2A04);

instead of these 128 bit UUIDs as stated in the documentation:

00002A00-0000-1000-8000-00805F9B34FB
00002A01-0000-1000-8000-00805F9B34FB
00002A04-0000-1000-8000-00805F9B34FB

The 128 bit versions do not work, only the 16 bit do work. In general the BLE library for ESP32 that I am using can handle both 16 and 128 bit UUIDs and it works. So I am a bit confused.

2) The "0783b03e-8535-b5a0-7140-a304d2495cb7" UUID (ActiveLook® Commands Interface) in the documenation has a "0x" in front of it. I think this is not consistent with a policy where the 16 bit UUIDs do have "0x" and the 128 bit do not have.

**Comment by tcubizolle-microoled** [comment]
Hello,

1) The registered UUID can be shortened to 16bit with the following method;
128bit: `0000xxxx-0000-1000-8000-00805F9B34FB` where xxxx is the 16bit value

For device name both `00002a00-0000-1000-8000-00805f9b34fb` and `0x2a00` are correct.

More information are available here: [Core Specification 5.3](https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=521059)

2) Thanks for the feedback. It will be fixed in the next version of the documentation.

**Comment by toncho11** [comment]
1) Last time I could not make the 128 bit version work. 

Thank you for your quick response.
